defaults:
    - _self_
    - data: default.yaml
    - paths: default.yaml
    - logger: null
    - evolution: default.yaml
    - crossover: default.yaml
    - mutation: default.yaml
    - selection: default.yaml
    - local_search: default.yaml

    - experiment: null

draw_graph: False

input_file: null

seed: 64
tags: []