defaults:
  - _self_
  - data: default.yaml
  - paths: default.yaml
  - logger: null
  - evolution: default.yaml
  - crossover: default.yaml
  - mutation: default.yaml
  - selection: default.yaml
  - local_search: default.yaml

draw_graph: False

seed: 64
tags: []