defaults:
    - _self_
    - data: default.yaml
    - paths: default.yaml
    - logger: null
    - local_search: ls_experiment.yaml
    - mutation: ls_mutation.yaml

visualize: False
draw_graph: False

seed: 64
tags: []